stages:
    - build
    - checkstyle

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/Sisu/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true  

java-build-and-test:
    image: "maven:3.6.3-openjdk-11"
    stage: build
    cache:
        key: "maven-$CI_COMMIT_REF_SLUG"
        paths:
            - .m2/repository
    script:
        - echo "Building project"
        - cd Sisu/
        - mvn $MAVEN_CLI_OPTS verify

    artifacts:
        name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
        paths:
        - "**/target"
        reports:
            # declare the JUnit reports (recursive pattern for multi-module projects)
            junit:
                - "**/target/*-reports/TEST-*.xml"

checkstyle:
    stage: checkstyle
    image: maven:3.6.3-jdk-11
    script: mvn checkstyle:checkstyle
